trigger:
  - main
  - develop

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    displayName: 'Build & Test'
    jobs:
      - job: BuildJob
        displayName: 'Flutter Build'
        steps:
          - task: FlutterInstall@0
            displayName: 'Install Flutter'

          - script: flutter pub get
            displayName: 'Get Dependencies'

          - script: flutter test
            displayName: 'Run Tests'

          - script: flutter build apk
            displayName: 'Build APK'
