trigger:
  - main
  - develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  javaVersion: '17'

stages:
  - stage: Build
    displayName: 'Build & Test'
    jobs:
      - job: BuildJob
        displayName: 'Java Build'
        steps:
          - task: JavaToolInstaller@0
            inputs:
              versionSpec: $(javaVersion)
            displayName: 'Install Java'

          - script: mvn clean install
            displayName: 'Build and Test'

          - script: mvn package
            displayName: 'Package Application'
